/**
 * Phase 7 — Revenue timeline event types (§6.2).
 */
export enum RevenueTimelineEventType {
  ISSUE_DETECTED = "ISSUE_DETECTED",
  IMPACT_ESTIMATED = "IMPACT_ESTIMATED",
  ACTION_RECOMMENDED = "ACTION_RECOMMENDED",
  APPROVAL_REQUESTED = "APPROVAL_REQUESTED",
  APPROVAL_GRANTED = "APPROVAL_GRANTED",
  APPROVAL_REJECTED = "APPROVAL_REJECTED",
  ACTION_EXECUTED = "ACTION_EXECUTED",
  ACTION_FAILED = "ACTION_FAILED",
  ACTION_PARTIALLY_SUCCEEDED = "ACTION_PARTIALLY_SUCCEEDED",
  VERIFICATION_STARTED = "VERIFICATION_STARTED",
  VERIFICATION_SUCCEEDED = "VERIFICATION_SUCCEEDED",
  VERIFICATION_FAILED = "VERIFICATION_FAILED",
  REVENUE_RECOVERED = "REVENUE_RECOVERED",
  LOSS_AVOIDED = "LOSS_AVOIDED",
  OPERATIONAL_SAVINGS_RECORDED = "OPERATIONAL_SAVINGS_RECORDED",
  ISSUE_CLOSED = "ISSUE_CLOSED",
  ISSUE_REOPENED = "ISSUE_REOPENED",
  TIMELINE_CORRECTION = "TIMELINE_CORRECTION",
}
