/**
 * Phase 2 — Simulation types.
 */
export enum SimulationType {
  POLICY_PREVIEW = "POLICY_PREVIEW",
  PLAYBOOK_BACKTEST = "PLAYBOOK_BACKTEST",
  WORKFLOW_REPLAY = "WORKFLOW_REPLAY",
  THRESHOLD_COMPARISON = "THRESHOLD_COMPARISON",
  DEMO_SCENARIO = "DEMO_SCENARIO",
}
