/**
 * Phase 1 — Lifecycle event type constants.
 */
export enum IssueLifecycleEventType {
  ISSUE_DETECTED = "ISSUE_DETECTED",
  IMPACT_ESTIMATION_RECORDED = "IMPACT_ESTIMATION_RECORDED",
  ACTION_PLAN_CREATED = "ACTION_PLAN_CREATED",
  ACTION_EXECUTION_RECORDED = "ACTION_EXECUTION_RECORDED",
  VERIFICATION_REQUESTED = "VERIFICATION_REQUESTED",
  VERIFICATION_COMPLETED_SUCCESS = "VERIFICATION_COMPLETED_SUCCESS",
  VERIFICATION_COMPLETED_FAILURE = "VERIFICATION_COMPLETED_FAILURE",
  NO_ACTION_DECISION_RECORDED = "NO_ACTION_DECISION_RECORDED",
  TERMINAL_CLASSIFICATION_RECORDED = "TERMINAL_CLASSIFICATION_RECORDED",
  ISSUE_CLOSED = "ISSUE_CLOSED",
  ISSUE_REOPENED = "ISSUE_REOPENED",
  LIFECYCLE_VALIDATION_FAILED = "LIFECYCLE_VALIDATION_FAILED",
}
